#!/bin/sh
# cat all non-commented files listed in .build into a single distribution file
cat src/.build | grep "^[^#]" | sed -r s-(\w*)-src/\1.js- | xargs cat > dist/livity.js

# and then transpile and minify everything
babel --extensions=.js --source-maps=true --no-babelrc --minified --compact=true --presets=es2015 ../dist/*.js # --out-dir public/js/build
